FROM node:22
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install
RUN npm install react-big-calendar moment
COPY frontend/ ./
EXPOSE 5173
CMD ["npx", "vite", "--host", "0.0.0.0", "--port", "5173"]